name: Artifacts Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Files
        run: |
          echo "Creating file1.txt..."
          echo "Content for file1" > file1.txt
          
          mkdir folder
          echo "Creating folder/file2.txt..."
          echo "Content for file2" > folder/file2.txt

      - name: Store Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: |
            file1.txt
            folder/file2.txt
